project:
  type: website

website:
  title: "Estadística Descriptiva multivariada"
  navbar:
    left:
      - href: index.qmd
        text: Información grupo
      - TallerUno.qmd
      - TallerDos.qmd
      - TallerTres.qmd
      - TallerCuatro.qmd
      - TallerQuinto.qmd


format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual


